version: 0.2

phases:
  install:
    commands:
      - echo Start building radiogram-consumer-lambda-app on `date`...
      - npm install mocha -g
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post-build:
    commands:
      - echo Packaging radiogram-consumer-lambda-app...
      - aws cloudformation package --template-file template.yaml --s3-bucket radiogram-consumer-lambda-app --output-template-file packaged-template.yaml
artifacts:
  files:
    - template.yaml
    - packaged-template.yaml