version: 0.2

phases:
  install:
    commands:
      - echo Build completed on `date`.
  pre_build:
    commands:
      - echo required ENV variables REQUEST_QUEUE_ARN = $REQUEST_QUEUE_ARN, RESPONSE_QUEUE_URI = $RESPONSE_QUEUE_URI
  build:
    command:
      - echo Start building radiogram-consumer-lambda-app ...
      - npm install
      - echo Packaging radiogram-consumer-lambda-app...
      - aws cloudformation package --template-file template.yaml --s3-bucket radiogram-consumer-lambda-app --output-template-file packaged-template.yaml
      - aws cloudformation deploy --template-file packaged-template.yaml --stack-name cf-radiogram-cc-stack --parameter-override requestQueueArn=$REQUEST_QUEUE_ARN  responseQueueUri=$RESPONSE_QUEUE_URI --capabilities CAPABILITY_IAM
artifacts:
  files:
    - template.yaml
    - packaged-template.yaml